name: Run pytest before merging to master

on:
  # run when a pull request is opened
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run pytest
        # go into the tests directory and run pytest
        env:
          LECTIO_USERNAME: ${{ secrets.LECTIO_USERNAME }}
          LECTIO_PASSWORD: "${{ secrets.LECTIO_PASSWORD }}"
          LECTIO_SCHOOL_ID: ${{ secrets.LECTIO_SCHOOL_ID }}
        run: |
          pip install pytest
          cd tests
          pytest lectioscraper_tests.py